### ISSUE TITLE
这个查询速度如何？查询返回的结果数据格式是什么样的？

### ISSUE THREAD

**Issue by TARFighting** [tagphi/czdb-search-java#1]
这个和ip2region返回的region信息一样吗？类似于 _**国家|区域|省份|城市|ISP**_  这种格式的？查询速度如何？
因为使用需要先获得纯真社区授权，文档里也没有提到这些信息，如果有人想先了解一些信息再决定要不要使用的话，就会比较难办，希望可以完善一下文档，感谢

**Comment by tiandikurong** [comment]
我刚试了一下，打印出来的结果是这样的“美国–加利福尼亚州–圣克拉拉–山景城	谷歌公司DNS服务器”
![image](https://github.com/tagphi/czdb-search-java/assets/48670105/48d9dd65-6478-440b-9ab5-5a25e5d9d2ad)

**Comment by tiandikurong** [comment]
> 这个和ip2region返回的region信息一样吗？类似于 _**国家|区域|省份|城市|ISP**_ 这种格式的？查询速度如何？
> 因为使用需要先获得纯真社区授权，文档里也没有提到这些信息，如果有人想先了解一些信息再决定要不要使用的话，就会比较难办，希望可以完善一下文档，感谢

我今天简单试了一下，可以看一下：https://blog.csdn.net/tiandikurong/article/details/140336711?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22140336711%22%2C%22source%22%3A%22tiandikurong%22%7D

**Comment by anhao** [comment]
格式：
中国–江苏–南京	南京信风网络科技有限公司

**Comment by craigliu** [comment]
返回的字符串格式为 "国家–省份–城市–区域 ISP"。例如，对于一个位于中国上海市虹口区的IP地址，返回的字符串可能是 "中国–上海–上海–虹口区 电信"。如果搜索失败，它将返回 null。
