### ISSUE TITLE
v4和v6是分别读取吗

### ISSUE THREAD

**Issue by wnhyang** [tagphi/czdb-search-java#10]
示例里讲的new DbSearcher，path是单个文件的路径吗？需要解析v4时使用cz88_public_v4.czdb路径，需要解析v6时使用cz88_public_v6.czdb是吗？创建两个DbSearcher对象，还是什么？

**Comment by craigliu** [comment]
是的 现在社区版本已经发布了一个v6的版本，公众号里有说明应该

**Comment by kowhi** [comment]
v6版本目前只能查询到中国，不能到省市区呀

**Comment by craigliu** [comment]
> v6版本目前只能查询到中国，不能到省市区呀

v6社区版目前是比较粗糙的，数据有社区成员贡献。如果商业使用，可以购买cz88商业离线库版本
