### ISSUE TITLE
V6不支持省市区

### ISSUE THREAD

**Issue by kowhi** [tagphi/czdb-search-java#11]
使用最新版本1.0.2.2，解析ipv6地址，“2408:4005:3ba:934b:f9e6:e8ba:640b:a6b3”只显示“中国	Alibaba.com LLC”，无法到省市区

**Comment by craigliu** [comment]
社区办现在v6地址是比较粗糙的，数据社区成员贡献的。欢迎提供数据。

如果需要商业用途，可以购买精确的cz88商业版本
