### ISSUE TITLE
ipv6地址无法获取

### ISSUE THREAD

**Issue by mnlmc** [tagphi/czdb-search-java#13]
1、我使用下载的jar包czdb-search-1.0.jar  czdb-search-1.0.2.5.jar都无法解析ipv6的地址
2、使用自己编码，同样无法解析且报错
![Snipaste_2024-11-05_10-50-20](https://github.com/user-attachments/assets/1f32e37b-7e47-457c-a409-b6f9829d0f5f)
<img width="481" alt="Snipaste_2024-11-05_10-52-06" src="https://github.com/user-attachments/assets/5237a49e-b316-4cd6-b7c5-ebcf914ec837">

**Comment by gaogaoyt** [comment]
> 1、我使用下载的jar包czdb-search-1.0.jar czdb-search-1.0.2.5.jar都无法解析ipv6的地址 2、使用自己编码，同样无法解析且报错 ![Snipaste_2024-11-05_10-50-20](https://private-user-images.githubusercontent.com/52947694/382988811-1f32e37b-7e47-457c-a409-b6f9829d0f5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTI5NDIsIm5iZiI6MTczMTQ5MjY0MiwicGF0aCI6Ii81Mjk0NzY5NC8zODI5ODg4MTEtMWYzMmUzN2ItN2U0Ny00NTdjLWE0MDktYjZmOTgyOWQwZjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDEwMTA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YmY4NWNmMzUzOGNkZDFlOTJhZTY3OWFmZjk2Y2MxOWY0YjhkY2YzNGY4YmIwMmM0ZDg4MTAxOGQyYjIwOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Za8lyKHht-FRr8BaOWNGkDi-VjFcqSY5Fhps32NDLn0) <img alt="Snipaste_2024-11-05_10-52-06" width="481" src="https://private-user-images.githubusercontent.com/52947694/382989104-5237a49e-b316-4cd6-b7c5-ebcf914ec837.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTI5NDIsIm5iZiI6MTczMTQ5MjY0MiwicGF0aCI6Ii81Mjk0NzY5NC8zODI5ODkxMDQtNTIzN2E0OWUtYjMxNi00Y2Q2LWI3YzUtZWJjZjkxNGVjODM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDEwMTA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNjhkMTJlZmEzYTE2ZGNjNDY0MGEwNTExYjM3YzNmN2Y1ZGJiMWI1ZmM5NzY0MzU3MDc3NmI1MjM2NTRlNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rAyIO_szCQmTGmDiFrZqvMhaWE0dr2IgmoCXCftpukc">

试了下1.0.2.5的jar，截图中的ipv6地址是可以查的

**Comment by craigliu** [comment]
你看看是不是你查的库不对？ipv4和ipv6是两个不同的库 查ipv6需要用ipv6的czdb
