### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by wei1143366591** [tagphi/czdb-search-java#5]
java -cp czdb-search-1.0.jar net.cz88.czdb.SearcherTest -d 纯真社区版IP库v20240724.czdb -t MEMORY -k h102RWHmVoyFSIl-O5H3rA==
错误: 找不到或无法加载主类 net.cz88.czdb.SearcherTest

**Comment by craigliu** [comment]
现在版本是1.0.2.1去release下下载最新jar
