### ISSUE TITLE
Maven 插件 maven-shade-plugin 导致的冲突是否可以删除？

### ISSUE THREAD

**Issue by renfei** [tagphi/czdb-search-java#8]
我自己找到了 Spring Boot 中 Log 冲突的原因，关联 Issue #6 #7 我就关闭了。

# 问题

在 Spring Boot 中引入依赖，报错：

```
Exception in thread "main" java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.slf4j.helpers.NOPLoggerFactory loaded from file:/Users/renfei/.m2/repository/net/cz88/czdb-search/1.0.2.1/czdb-search-1.0.2.1.jar). If you are using WebLogic you will need to add 'org.slf4j' to prefer-application-packages in WEB-INF/weblogic.xml: org.slf4j.helpers.NOPLoggerFactory
	at org.springframework.util.Assert.instanceCheckFailed(Assert.java:592)
	at org.springframework.util.Assert.isInstanceOf(Assert.java:511)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerContext(LogbackLoggingSystem.java:401)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.beforeInitialize(LogbackLoggingSystem.java:128)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationStartingEvent(LoggingApplicationListener.java:238)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:220)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$starting$0(SpringApplicationRunListeners.java:54)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
	at net.renfei.czdbspringboottest.CzdbSpringBootTestApplication.main(CzdbSpringBootTestApplication.java:10)
```

是因为 slf4j 日志框架冲突了，我就开始寻找原因

## 寻找过程

查看 Maven 依赖图，发现 ```czdb-search``` 没有任何对外依赖？

![image](https://github.com/user-attachments/assets/69ab48b5-1657-4a7d-84f3-58c0176cdb95)

但 pom 中依赖了 ```slf4j-api```

```xml
    <dependencies>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${sl4j-api.version}</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>commons-cli</groupId>
            <artifactId>commons-cli</artifactId>
            <version>1.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.msgpack</groupId>
            <artifactId>msgpack-core</artifactId>
            <version>0.9.8</version>
        </dependency>
    </dependencies>
```

让我误以为源码和中央仓库中的包不一致，我自己 clone 源码尝试打自己的包，发现还是一样，Jar 包中携带依赖的源码，而不是在 pom 中依赖，所以是因为```maven-shade-plugin```插件打出了胖Jar：

```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>1.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>net.cz88.czdb.SearcherTest</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

## 如何解决

就是了为了让测试可以一个 Jar 包就可以运行，就把依赖库一起打入到 Jar 包中了？？

上面的插件虽然排除了 package 阶段，但 deploy 阶段正式向中央仓库发布时，还是打了个胖Jar。

是否可以放弃这么做？如果这样做，我其他项目中使用 ```executions``` 也无法排除Jar中的依赖。

建议将测试代码单独打包。

**Comment by renfei** [comment]
使用 Spring Boot 的同学，可以先试试我的：

```xml
<dependency>
    <groupId>net.renfei</groupId>
    <artifactId>czdb-search</artifactId>
    <version>1.0.2.1</version>
</dependency>
```

https://github.com/renfei/czdb-search-java

打包瘦Jar，移除 maven-shade-plugin 插件，重新发布

等待原作者解决

**Comment by craigliu** [comment]
好我知道了，maven-shade-plugin是在发布到maven的时候需要的插件，可以在生成的jar中排除。我晚点做个更新

**Comment by craigliu** [comment]
> 我自己找到了 Spring Boot 中 Log 冲突的原因，关联 Issue #6 #7 我就关闭了。
> 
> # 问题
> 在 Spring Boot 中引入依赖，报错：
> 
> ```
> Exception in thread "main" java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.slf4j.helpers.NOPLoggerFactory loaded from file:/Users/renfei/.m2/repository/net/cz88/czdb-search/1.0.2.1/czdb-search-1.0.2.1.jar). If you are using WebLogic you will need to add 'org.slf4j' to prefer-application-packages in WEB-INF/weblogic.xml: org.slf4j.helpers.NOPLoggerFactory
> 	at org.springframework.util.Assert.instanceCheckFailed(Assert.java:592)
> 	at org.springframework.util.Assert.isInstanceOf(Assert.java:511)
> 	at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerContext(LogbackLoggingSystem.java:401)
> 	at org.springframework.boot.logging.logback.LogbackLoggingSystem.beforeInitialize(LogbackLoggingSystem.java:128)
> 	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationStartingEvent(LoggingApplicationListener.java:238)
> 	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:220)
> 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
> 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
> 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
> 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
> 	at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
> 	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:75)
> 	at org.springframework.boot.SpringApplicationRunListeners.lambda$starting$0(SpringApplicationRunListeners.java:54)
> 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
> 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
> 	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:54)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
> 	at net.renfei.czdbspringboottest.CzdbSpringBootTestApplication.main(CzdbSpringBootTestApplication.java:10)
> ```
> 
> 是因为 slf4j 日志框架冲突了，我就开始寻找原因
> 
> ## 寻找过程
> 查看 Maven 依赖图，发现 `czdb-search` 没有任何对外依赖？
> 
> ![image](https://private-user-images.githubusercontent.com/6532952/358492058-69ab48b5-1657-4a7d-84f3-58c0176cdb95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTc0NzAsIm5iZiI6MTcyNTI1NzE3MCwicGF0aCI6Ii82NTMyOTUyLzM1ODQ5MjA1OC02OWFiNDhiNS0xNjU3LTRhN2QtODRmMy01OGMwMTc2Y2RiOTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDJUMDYwNjEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDg0YmI0YzEwZGY3Y2M0ZmQ0ZTM5NzdkY2U1YTUzNjJiYzA3MTE3YzQyMWZjZjEzODljM2Y1OTAxNDQ3NDZmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HZK9abaPP0Y0SkbCZxxRhmSP5WCPzftJcZtqh72o3C0)
> 
> 但 pom 中依赖了 `slf4j-api`
> 
> ```
>     <dependencies>
>         <dependency>
>             <groupId>org.slf4j</groupId>
>             <artifactId>slf4j-api</artifactId>
>             <version>${sl4j-api.version}</version>
>         </dependency>
>         <dependency>
>             <groupId>junit</groupId>
>             <artifactId>junit</artifactId>
>             <version>4.13</version>
>             <scope>test</scope>
>         </dependency>
>         <dependency>
>             <groupId>commons-cli</groupId>
>             <artifactId>commons-cli</artifactId>
>             <version>1.3.1</version>
>         </dependency>
>         <dependency>
>             <groupId>org.msgpack</groupId>
>             <artifactId>msgpack-core</artifactId>
>             <version>0.9.8</version>
>         </dependency>
>     </dependencies>
> ```
> 
> 让我误以为源码和中央仓库中的包不一致，我自己 clone 源码尝试打自己的包，发现还是一样，Jar 包中携带依赖的源码，而不是在 pom 中依赖，所以是因为`maven-shade-plugin`插件打出了胖Jar：
> 
> ```
>             <plugin>
>                 <groupId>org.apache.maven.plugins</groupId>
>                 <artifactId>maven-shade-plugin</artifactId>
>                 <version>1.4</version>
>                 <executions>
>                     <execution>
>                         <phase>package</phase>
>                         <goals>
>                             <goal>shade</goal>
>                         </goals>
>                         <configuration>
>                             <transformers>
>                                 <transformer
>                                         implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
>                                     <mainClass>net.cz88.czdb.SearcherTest</mainClass>
>                                 </transformer>
>                             </transformers>
>                         </configuration>
>                     </execution>
>                 </executions>
>             </plugin>
> ```
> 
> ## 如何解决
> 就是了为了让测试可以一个 Jar 包就可以运行，就把依赖库一起打入到 Jar 包中了？？
> 
> 上面的插件虽然排除了 package 阶段，但 deploy 阶段正式向中央仓库发布时，还是打了个胖Jar。
> 
> 是否可以放弃这么做？如果这样做，我其他项目中使用 `executions` 也无法排除Jar中的依赖。
> 
> 建议将测试代码单独打包。

我加了一个fatjar的profile。放到maven central的profile现在不用使用shade plugin了。版本1.0.2.3 你们试试看呢

**Comment by renfei** [comment]
Hi, @craigliu 

在中央仓库中未见到 1.0.2.3 啊：

https://repo1.maven.org/maven2/net/cz88/czdb-search/

**Comment by craigliu** [comment]
> Hi, @craigliu
> 
> 在中央仓库中未见到 1.0.2.3 啊：
> 
> https://repo1.maven.org/maven2/net/cz88/czdb-search/

现在应该有了，上次发布没成功

**Comment by renfei** [comment]
1.0.2.3 我这里测试可以的
